name: Full test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Start miminet (back)
        run: |
          cd back/
          docker compose up -d

      - name: Start miminet (front)
        run: |
          cd front/
          sed -i 's/MODE=prod/MODE=dev/' .env
          docker compose up -d

      - name: Wait for services to start
        run: sleep 10

      - name: Check availability
        run: |
          curl -f localhost
    
      - name: Start selenium
        run: |
           cd front/tests/docker
           docker compose up -d

      - name: Run tests
        run: |
           pytest front/tests